const db = require('../src/db');
const { writeFile } = require('then-fs');

const instructions = `DO NOT EDIT\nGenerated by scripts/generate_slots.js\n\n`;
const divider = '-- SLOT --';

async function generateSlots() {
  const books = await db.getBooks();

  const slots = [{
    name: 'booktitle',
    values: books.map(b => b.title),
  }];
  const content = instructions + slots.map(({name, values}) => {
    return `${divider}\n${name.toUpperCase()}\n\n${values.map(v => v.toLowerCase()).join('\n')}`
  }).join('\n\n\n');

  await writeFile('slots', content);
  process.exit();
}

generateSlots()
  .catch(error => console.log(error));
